import type { Bean, CatKey } from './types';

export const CATS: { key: CatKey; label: string; en: string }[] = [
  { key: 'clean', label: '乾淨度', en: 'Clean Cup' },
  { key: 'sweet', label: '甜感', en: 'Sweetness' },
  { key: 'acid', label: '酸質', en: 'Acidity' },
  { key: 'mouth', label: '口感', en: 'Mouthfeel' },
  { key: 'flavor', label: '風味', en: 'Flavor' },
  { key: 'after', label: '餘韻', en: 'Aftertaste' },
  { key: 'balance', label: '平衡', en: 'Balance' },
  { key: 'overall', label: '整體', en: 'Overall' },
];

export const DEFAULT_ACTIVITY = '咖啡社杯測';

// Continent/region-level options for LEADERBOARD mode's "Area" category —
// distinct from ORIGINS below, which is country/region-level ("Country").
// Curated by hand (leaderboard.coffee's tasting cards use a short fixed list
// like this, unlike the long free-text-friendly ORIGINS list).
export const AREAS = [
  'Africa',
  'Asia',
  'Caribbean',
  'Central America',
  'North America',
  'Oceania',
  'South America',
];

// Country options, grouped by AREA above so the Country picker can filter
// to just the selected continent. Countries here started as a flat list
// seeded from Loffee Labs' public /origins lookup (https://loffeelabs.com)
// merged with this project's original curated set; area-meta entries that
// leaked into that flat list ("African", "Americas", "Central America",
// "East Asia", "Latin America") were dropped since they duplicate AREAS
// itself rather than naming an actual country/region.
export const COUNTRIES_BY_AREA: Record<string, string[]> = {
  Africa: [
    'Burundi',
    'Democratic Republic Of The Congo',
    'DR Congo',
    'Ethiopia',
    'Kenya',
    'Malawi',
    'Rwanda',
    'South Africa',
    'Sudan',
    'Tanzania',
    'Uganda',
    'Zambia',
  ],
  Asia: [
    'China',
    'India',
    'Indonesia',
    'Laos',
    'Malaysia',
    'Myanmar',
    'Nepal',
    'Philippines',
    'Sumatra',
    'Taiwan',
    'Thailand',
    'Timor Leste',
    'Vietnam',
    'Yemen',
  ],
  Caribbean: ['Jamaica'],
  'Central America': ['Costa Rica', 'El Salvador', 'Guatemala', 'Honduras', 'Mexico', 'Nicaragua', 'Panama'],
  'North America': ['California', 'Hawai‘i', 'United States'],
  Oceania: ['Australia', 'Papua New Guinea'],
  'South America': ['Bolivia', 'Brazil', 'Colombia', 'Ecuador', 'Peru', 'Venezuela'],
};

/** Country options for a given Area; falls back to every country when area is blank/unrecognized. */
export function countriesForArea(area: string): string[] {
  return COUNTRIES_BY_AREA[area] ?? ORIGINS;
}

export const ORIGINS = Object.values(COUNTRIES_BY_AREA).flat();

// Simplified to just the three broad categories cuppers actually distinguish
// by taste — the previous ~130-option list (Loffee Labs' full process
// taxonomy) was too granular for a quick guess.
export const PROCESSES = ['水洗', '蜜處理', '日曬'];

export const VARIETIES = [
  "Ab-Grade",
  "Abyssinia",
  "Acaia",
  "Acaua",
  "Aji",
  "Amarillo",
  "Anacafe 14",
  "Andung Sari",
  "Arabica",
  "Arabica S274",
  "Aramosa",
  "Arara",
  "Arusha",
  "Aruzi",
  "Ateng",
  "Ateng Coklat",
  "Ateng Ijo",
  "Ateng Super",
  "B7",
  "Batian",
  "Bernardina",
  "Blend",
  "Blue Mountain",
  "Bor Bor",
  "Borbon Sutil (Pink Bourbon)",
  "Bourbon",
  "Bourbon Aji",
  "Bourbon Amarelo (Yellow Bourbon)",
  "Bourbon Amarillo (Yellow Bourbon)",
  "Bourbon De Colasay",
  "Bourbon Elite",
  "Bourbon L9",
  "Bourbon Mayaguez 139",
  "Bourbon Mayaguez 71",
  "Bourbon Pimienta",
  "Bourbon Pointu (Laurina)",
  "Bourbon Primitivo",
  "Bourbon Rojo (Red Bourbon)",
  "Bourbon Rosado (Pink Bourbon)",
  "Bourbon Varieties",
  "Bourboncito (B300)",
  "BourbonNaranja (Orange Bourbon)",
  "Castillo",
  "Castillo El Tambo",
  "Castillo Naranjal",
  "Catigua",
  "Catigua Mg2",
  "Catimor",
  "Catimor P3",
  "Catimor P4",
  "Catimor P4 (7963)",
  "Catiope",
  "Catisic",
  "Catuai",
  "Catuai 144",
  "Catuai 99",
  "Catuai Amarillo (Yellow Catuai)",
  "Catuai Rojo (Red Catuai)",
  "Catucai",
  "Catucai 2Sl",
  "Catucai 785",
  "Caturra",
  "Caturra Chiroso",
  "Caturra Field Blend",
  "Caturra Hybrid",
  "Caturra X Catuai",
  "Caturro",
  "Caturro Chiroso",
  "Caturron",
  "Cauvery",
  "Cenicafe",
  "Cenicafe1",
  "Cgle",
  "Cgle-17",
  "Chandragiri (Sarchimor)",
  "Chandragiri (Sl13)",
  "Chiang Mai",
  "Chicho Gallo",
  "Chiroso",
  "Cobra",
  "Colombia",
  "Colombia Rosado (Pink Colombia)",
  "Costa Rica 95",
  "Criollo (Typica)",
  "Cxr Robusta",
  "Dawairi",
  "Dega",
  "Dilla Alghe",
  "Dwarf Bourbon",
  "Elefante",
  "Elite Bourbon",
  "Enat Buna",
  "Esperanza",
  "Ethiopia 47",
  "Ethiopian Heirlooms",
  "Ethiopian Landraces",
  "Ethiosar",
  "Eugenioides",
  "Excelsa",
  "F1",
  "F1 Hybrid",
  "F6 (Colombia)",
  "Field Blend",
  "Fine Robusta",
  "French Mission Bourbon",
  "Garnica",
  "Gayo",
  "Gayo 1",
  "Gayo 2",
  "Geisha",
  "Geisha 1931",
  "Geisha Peaberry",
  "Geisha Rojo (Red Geisha)",
  "Gemadro",
  "Gera",
  "Gesha",
  "Gesha 2722",
  "Gesha Enano (Dwarf Gesha)",
  "Gesha Inca",
  "Gesha1931",
  "Gibirinna (Jarc 74110)",
  "Gibirinna (Jarc 74110) Jarc 74110 Serto Jarc 74112",
  "Gori Geisha",
  "Gori Gesha",
  "Green Tip Geisha",
  "Green Tip Gesha",
  "Guará",
  "Guarani",
  "H-Grade",
  "H1 Centroamericano",
  "H10 (Milenio)",
  "H17",
  "H17 Hybrid",
  "H3",
  "Harrar Longberry",
  "Heirloom (Ethiopia)",
  "Heirloom Ethiopian Varieties",
  "Heirloom Hybrid 1",
  "Heirlooms",
  "Heirlooms Ethiopian Heirlooms",
  "Hemavathi",
  "Hybrids",
  "Ibc 12",
  "Icatu",
  "Ihcafe 90",
  "Indigenous Heirloom",
  "Indigenous Landraces",
  "Indigenous Selections",
  "Ipr 98",
  "Isolated",
  "Ja'Adi",
  "Jackson Bourbon",
  "Jarc 74100",
  "Jarc 74110",
  "Jarc 74110 (Gibirinna)",
  "Jarc 74112",
  "Jarc 74114",
  "Jarc 74140",
  "Jarc 74148",
  "Jarc 74158",
  "Jarc 74158 (Walega)",
  "Jarc 74158 Kurume",
  "Jarc 74165",
  "Jarc 7440",
  "Jarc 7454",
  "Jarc 75148",
  "Jarc 75210",
  "Jarc Selections",
  "Jarc Varieties",
  "Java",
  "Javanica",
  "Jember (S795)",
  "K7",
  "Kartika",
  "Kent",
  "Kenya Varieties",
  "Kenyan",
  "Kilimanjaro",
  "Kimono",
  "Kona Typica",
  "Kp423",
  "Kurume",
  "Landraces",
  "Laurina",
  "Lempira",
  "Liberica",
  "Limonares",
  "Lini S (S795)",
  "Local Landraces",
  "Luwiro",
  "Malawi Gesha",
  "Mamut",
  "Mandela",
  "Maracaturra",
  "Maragesha",
  "Maragogipe",
  "Maragogype",
  "Marcellesa",
  "Mariana (Iapar Ethiopian)",
  "Marsellesa",
  "Marshell",
  "Mejorado",
  "Merdacheriko",
  "Metu Bishari",
  "Mibirizi",
  "Mikicho",
  "Moka",
  "Mokka",
  "Mulungu",
  "Mundo Maya (H16)",
  "Mundo Novo",
  "Mysore",
  "N39",
  "Nyanzaland",
  "Nyasaland",
  "Obata",
  "Ombligon",
  "Orange Bourbon",
  "Orange Geisha",
  "Orange Gesha",
  "Orange Tabi",
  "Orange Wush Wush",
  "Oro Azteca",
  "P88",
  "Pacamara",
  "Pacas",
  "Pache",
  "Pache San Ramon",
  "Pache Verde (Green Pache)",
  "Papayo",
  "Parainema",
  "Paraiso",
  "Peaberry",
  "Peñasco",
  "Pink Bourbon",
  "Pink Geisha",
  "Pink Gesha",
  "Pl122",
  "Plume Hidalgo",
  "Portillo",
  "Purple Caturra",
  "Rab C15",
  "Red",
  "Red Bourbon",
  "Red Catuai",
  "Red Catucai",
  "Red Caturra",
  "Red Geisha",
  "Red Gesha",
  "Red Obata",
  "Red Pacamara",
  "Red Pacas",
  "Red Striped Bourbon",
  "Red Tabi",
  "Robusta",
  "Robusta Cxr",
  "Rosado (Pink Bourbon)",
  "Rubi",
  "Ruiru 11",
  "Rume Sudan",
  "S795",
  "San Bernado (Pache)",
  "San Bernardo",
  "San Isidro",
  "San Isidro 48",
  "San Juan",
  "San Pacho",
  "San Ramon",
  "San Roque (Kenia)",
  "San Salvador",
  "Sarchimor (T5296)",
  "Selection 5B",
  "Serto",
  "Serto (Jarc 74112)",
  "Setami",
  "Sidra",
  "Sigarar Utang",
  "Sj133",
  "Sl Varieties",
  "Sl13",
  "Sl14",
  "Sl28",
  "SL28",
  "Sl34",
  "SL34",
  "Sl6",
  "Sl9",
  "Sl9 (Gesha Inca)",
  "Sln 9",
  "Starmaya",
  "Striped Bourbon",
  "Striped Red Bourbon",
  "Sudan Rume",
  "Super Madre Geisha",
  "Supremo",
  "Sydra",
  "Syrina",
  "Tabi",
  "Tacri Varieties",
  "Tekesic",
  "Tim Tim",
  "Timor Hybrid (Tim Tim)",
  "Topazio",
  "Tuffahi",
  "Tupi",
  "Typica",
  "Typica Americana (Typica)",
  "Typica Dawairy",
  "Typica Lima",
  "Typica Mejorado",
  "Udaini",
  "Usda 762",
  "V",
  "Variedad",
  "Variedad Colombia",
  "Venecia",
  "Villa Sarchi",
  "Villalobos",
  "Walega (Jarc 74158)",
  "Wolisho",
  "Wush Wush",
  "Yellow Bourbon",
  "Yellow Catuai",
  "Yellow Catuai 2Sl",
  "Yellow Catucai",
  "Yellow Caturra",
  "Yellow Caturro",
  "Yellow Geisha",
  "Yellow Gesha",
  "Yellow Icatu",
  "Yellow Maragogype",
  "Yellow Pacamara",
  "Yellow Pacas",
  "Yellow Papayo",
  "Yellow Sudan Rume",
  "Yellow Typica",
  "Yellow Variedad Colombia",
  "Yemenia",
];
;

export function scaleMin(baseScale: '4–8' | '0–8' = '4–8') {
  return baseScale === '0–8' ? 0 : 4;
}

export function sheetTotal(vals: Record<CatKey, number>, defInt: number, scoreMode: 'pro' | 'easy', easyScore: number) {
  if (scoreMode === 'easy') {
    return Math.min(100, Math.max(0, easyScore));
  }
  let sum = 36;
  CATS.forEach((c) => {
    sum += vals[c.key];
  });
  return sum - defInt;
}

export function beanSub(b: Bean) {
  return [b.area, b.origin, b.process, b.variety, b.elevation, b.decaf ? '低咖啡因' : '', b.producer, b.roaster]
    .filter(Boolean)
    .join(' · ');
}

export function fmtTime(sec: number) {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return String(m).padStart(2, '0') + ':' + String(s).padStart(2, '0');
}
